<?php

return [
    'levels' => [
        'superadmin' => [
            'label' => 'Super Admin',
            'description' => 'Full unrestricted access across the admin panel.',
            'patterns' => ['*'],
        ],
        'admin' => [
            'label' => 'Admin',
            'description' => 'Operational control over dashboard, users, roles, and permissions.',
            'patterns' => ['*'],
        ],
        'manager' => [
            'label' => 'Manager',
            'description' => 'Management access with read-heavy visibility and limited user operations.',
            'patterns' => [
                'Dashboard_View',
                'AboutUs_Menu',
                'AboutUs_ViewAll',
                'AboutUs_ViewMine',
                'AboutUs_View',
                'AboutUs_Edit',
                'Brand_Menu',
                'Brand_ViewAll',
                'Brand_ViewMine',
                'Brand_View',
                'Brand_Edit',
                'Category_Menu',
                'Category_ViewAll',
                'Category_ViewMine',
                'Category_View',
                'Category_Edit',
                'Faq_Menu',
                'Faq_ViewAll',
                'Faq_ViewMine',
                'Faq_View',
                'Faq_Edit',
                'Lease_Menu',
                'Lease_ViewAll',
                'Lease_ViewMine',
                'Lease_View',
                'Lease_Edit',
                'Location_Menu',
                'Location_ViewAll',
                'Location_ViewMine',
                'Location_View',
                'Location_Edit',
                'Testimonial_Menu',
                'Testimonial_ViewAll',
                'Testimonial_ViewMine',
                'Testimonial_View',
                'Testimonial_Edit',
                'User_*',
            ],
        ],
        'sales' => [
            'label' => 'Sales',
            'description' => 'Restricted front-office visibility focused on dashboard and basic user access.',
            'patterns' => [
                'Dashboard_View',
                'User_Menu',
                'User_ViewAll',
                'User_View',
                'Inquiry_Menu',
                'Inquiry_ViewAll',
                'Inquiry_View'
            ],
        ],
    ],
];
