<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Booking extends Model
{
    protected $table = 'bookings';

    protected $fillable = [
        'name',
        'number',
        'email',
        'start_date',
        'end_date',
        'start_time',
        'end_time',
        'rental_type',
        'rental_price',
        'rental_duration',
        'resident_tourist',
        'full_insurance',
        'full_insurance_price',
        'additional_driver',
        'additional_driver_charges',
        'baby_seat',
        'baby_seat_price',
        'deposit_waiver',
        'deposit_waiver_price',
        'delivery_location',
        'delivery_custom_address',
        'delivery_location_price',
        'different_city_dropoff_fee',
        'self_pickup_location_id',
        'self_pickup_location',
        'self_pickup_address',
        'return_location',
        'return_custom_address',
        'return_location_price',
        'self_return_location_id',
        'self_return_location',
        'self_return_address',
        'coupon_code',
        'coupon_amount',
        'pay_now_discount',
        'discount_percentage',
        'subtotal',
        'vat_percentage',
        'vat_amount',
        'total_amount',
        'payment_flow',
        'pay_now_20%_to_Reserve',
        'pay_at_pickup_80%',
        'paid_id',
        'paid_date',
        'paid_status',
        'paid_via',
        'contact_preference',
        'term_22_years',
        'term_6_month_experience',
        'send_booking_id',
        'notes',
        'speed_response',
    ];

    protected $casts = [
        'start_date' => 'date',
        'end_date' => 'date',
        'start_time' => 'string',
        'end_time' => 'string',
        'rental_price' => 'decimal:2',
        'full_insurance' => 'bool',
        'full_insurance_price' => 'decimal:2',
        'additional_driver' => 'bool',
        'additional_driver_charges' => 'decimal:2',
        'baby_seat' => 'bool',
        'baby_seat_price' => 'decimal:2',
        'deposit_waiver_price' => 'decimal:2',
        'delivery_location_price' => 'decimal:2',
        'different_city_dropoff_fee' => 'decimal:2',
        'return_location_price' => 'decimal:2',
        'coupon_amount' => 'decimal:2',
        'pay_now_discount' => 'decimal:2',
        'discount_percentage' => 'decimal:2',
        'subtotal' => 'decimal:2',
        'vat_percentage' => 'decimal:2',
        'vat_amount' => 'decimal:2',
        'total_amount' => 'decimal:2',
        'pay_now_20%_to_Reserve' => 'decimal:2',
        'pay_at_pickup_80%' => 'decimal:2',
        'paid_date' => 'datetime',
        'term_22_years' => 'bool',
        'term_6_month_experience' => 'bool',
    ];
}
